flink-extended/dl-on-flink

- flink-ml-tensorflow/src/main/java/com/alibaba/flink/ml/tensorflow/coding/ExampleCoding.java
- flink-ml-tensorflow/src/test/java/com/alibaba/flink/ml/tensorflow/coding/CodingUtils.java
- flink-ml-tensorflow/src/test/java/com/alibaba/flink/ml/tensorflow/coding/ExampleInputOutputTest.java
- flink-ml-tensorflow/src/test/python/example_coding.py
1. Fixed the bug of "Exception when there is only InputTfExampleConfig but no OutputTfExampleConfig(see issue #10 )" via adding null pointer checks in ExampleCoding.java
2. Add related test case for different situation of ExampleCoding
> [Bug fixed]Add null pointer checks when configure ExampleCoding

- flink-ml-tensorflow/src/main/java/com/alibaba/flink/ml/tensorflow/util/ExampleCodingConfigUtil.java
- flink-ml-tensorflow/src/test/java/com/alibaba/flink/ml/tensorflow/coding/ExampleCodingTest.java
What's changed:
1. Add an util class **ExampleCodingConfigUtil.java** which provide methods to configure example coding and methods to convert DataTypes and TypeInformation.
2. Add a **test** of ExampleCoding for table using above util class.
> [Enhancement] Add util to simplify the ExampleCoding configuration

- flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/proto/NotificationServiceGrpc.java
- flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/proto/NotificationServiceOuterClass.java
- flink-ai-flow/lib/notification_service/notification_service/base_notification.py
- flink-ai-flow/lib/notification_service/notification_service/client.py
- flink-ai-flow/lib/notification_service/notification_service/event_storage.py
- flink-ai-flow/lib/notification_service/notification_service/master.py
- flink-ai-flow/lib/notification_service/notification_service/mongo_event_storage.py
- flink-ai-flow/lib/notification_service/notification_service/mongo_notification.py
- flink-ai-flow/lib/notification_service/notification_service/proto/notification_service.proto
- flink-ai-flow/lib/notification_service/notification_service/proto/notification_service_pb2.py
- flink-ai-flow/lib/notification_service/notification_service/proto/notification_service_pb2_grpc.py
- flink-ai-flow/lib/notification_service/notification_service/service.py
- flink-ai-flow/lib/notification_service/notification_service/util/__init__.py
- flink-ai-flow/lib/notification_service/notification_service/util/db.py
- flink-ai-flow/lib/notification_service/notification_service/util/utils.py
- flink-ai-flow/lib/notification_service/tests/test_notification.py
This pull request upgrade the functionality of the notification service, which contains:
1. 2 more fields were added to the `BaseEvent`:
- `namespace`: The field used to isolate different workspaces:
i. When you create a notification client, you can specify a default namespace, or keep it None/null, which equivalent to namespace ""(empty string).
ii. The API `send_event`, `list_events`, `start_listen_event`, `stop_listen_event`, `get_latest_version` will only work on the default namespace and the data in other namespaces is invisible for them.
iii. The API `list_all_events`, `start_listen_events`, `stop_listen_events` will not affected by namespace, all data is visible for them.
- `context`: The field used to store the sender information which used to monitor.
2. remove `id` field and the …
> Upgrade the functionality of the notification service.

- deep-learning-on-flink/flink-ml-framework/src/main/java/com/alibaba/flink/ml/cluster/node/runner/CommonMLRunner.java
the cause of deadlock as belows:
1, when a worker have a failover and using FAILOVER_RESTART_ALL_STRATEGY, it will wait AM INIT status.
2, meanwhile, AM status will transit from RUNNING to AM_FAILOVER via FAIL_NODE event, then transit from AM_FAILOVER to AM_INIT with new version.
3, when the failover task request to AM with an old version, this request will be rejected. It will cause this worker lost forever, AM status stay in AM_INIT status forever.
> ! CommonMLRunner { fix the deadlock between a failover worker and am }

- flink-ai-flow/lib/notification_service/notification_service/mongo_notification.py
- flink-ai-flow/lib/notification_service/tests/test_mongo_notification.py
add sanity checks in mongo_notification.py, resolve some default values conflicts.
ex: listAllEventsRequest's end_version is default 0, it will cause list_all_events(_from_version) func return error result
> fix(ns-mongo-support):add more sanity checks

- flink-ai-flow/ai_flow/bin/stop-aiflow.sh
- flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
1. 移除了stop-aiflow.sh脚本中的rm -rf ${AIRFLOW_DEPLOY_PATH}，dag_dir删掉了dag会在数据库中被置为 not active，无法做状态恢复
2. 这里handle了除 RUNNING、QUEUED之外的 unfinished state, RUNNING、QUEUED交给executor恢复
> Recover task state after scheduler restart

- flink-ai-flow/ai_flow/rest_endpoint/service/client/aiflow_client.py
- flink-ai-flow/ai_flow/rest_endpoint/service/high_availability.py
- flink-ai-flow/ai_flow/store/mongo_store.py
- flink-ai-flow/ai_flow/store/sqlalchemy_store.py
- flink-ai-flow/lib/notification_service/notification_service/client.py
- flink-ai-flow/lib/notification_service/notification_service/util/db.py
- flink-ai-flow/lib/notification_service/notification_service/util/utils.py
Currently Python 3.6 doesn't support `time.time_ns()` method. For compatible with Python 3.6, `time.time_ns()` should be supported by the way as follows:
```
if not hasattr(time, 'time_ns'):
time.time_ns = lambda: int(time.time() * 1e9)
```
> compatible with Python 3.6

- flink-ai-flow/ai_flow/airflow/dag_generator.py
- flink-ai-flow/ai_flow/test/airflow/test_dag_generator.py
Flink AI Flow generates the Airflow DAG code of workflow, which code includes the unused `DummyOperator`. The generator could remove the `DummyOperator` code from the DAG.
> remove dummy operator

- flink-ai-flow/flink_ai_flow/local_flink_job.py
Fix bug in cancelling local flink job.
When we use requests api(urllib api in fact) in a forked process on mac, according to the [issue](https://bugs.python.org/issue30385), there will be a bug in proxy checking which makes it impossible to send REST requests.
As a result, the local flink job cannot be successfully cancelled.
- Set `os.environ['no_proxy'] = '*'` before calling requests.patch api 
> fix bug in cancelling local flink job

- flink-ai-flow/ai_flow/api/project.py
Currently, we use `os.rename` to move the generated airflow dag, which is in the /tmp folder, to the airflow deploy folder, It can cause problems when the airflow deploy folder is on a different file system than the /tmp folder. (https://docs.python.org/3/library/os.html#os.rename).
Therefore, we should use `shutil.move` to support moving dag files to a different filesystem.
- Use shutil.move in deploy_to_airflow
> [AIFlow] Use shutil.move to move airflow dag to airflow deploy folder

- deep-learning-on-flink/flink-ml-operator/src/main/java/com/alibaba/flink/ml/operator/ops/MLMapFunction.java
* Normally( **flatMap(IN value, Collector<OUT> out)** ), Python process produce data to  SpscQueue,  Java Process consume data from SpscQueue.
* In **close()**, before Python finished,  only Python write to SpscQueue, and there is no Java read from SpscQueue. if SpscQueue is not large enough, there is a chance that SpscQueue will be full. then Python will stuck in writing to SpscQueue.
* drainRead to EOF first, thus SpscQueue will not full and Python process will not stucking in writing.
> ! MLMapFunction  { close method: drainRead before future finish. }

- flink-ai-flow/ai_flow/bin/start-aiflow.sh
- flink-ai-flow/lib/airflow/airflow/api_connexion/endpoints/health_endpoint.py
- flink-ai-flow/lib/airflow/airflow/cli/cli_parser.py
- flink-ai-flow/lib/airflow/airflow/cli/commands/scheduler_command.py
- flink-ai-flow/lib/airflow/airflow/config_templates/default_airflow.cfg
- flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
- flink-ai-flow/lib/airflow/airflow/contrib/jobs/scheduler_factory.py
- flink-ai-flow/lib/airflow/airflow/utils/mailbox.py
- flink-ai-flow/lib/airflow/airflow/www/views.py
- flink-ai-flow/lib/airflow/tests/contrib/jobs/test_scheduler_factory.py
Fix #270 
1. Add a configuration ```scheduler = EventBasedSchedulerJob``` with default value ```SchedulerJob``` in airflow.cfg
2. Use ```airflow scheduler``` command to start both default scheduler and event_based scheduler, instead of airflow event_scheduler.
3. Move schedule loop from EventBasedScheduler to EventBasedSchedulerJob, send heartbeat during each loop. 
> [Flink AI Flow][Bug] EventBasedScheduler cannot send heartbeat

- flink-ai-flow/README.md
Rectify link of contribution guide in README.md
Modified flink-ai-flow/README.md
This change is a trivial rework without any test coverage.
> [Flink AI Flow] Rectify link of contribution guide in README.md

- flink-ai-flow/ai_flow/api/project.py
- flink-ai-flow/ai_flow/api/workflow_operation.py
- flink-ai-flow/ai_flow/graph/graph.py
- flink-ai-flow/ai_flow/test/api/test_airflow_job.py
- flink-ai-flow/ai_flow/test/master.yaml
- flink-ai-flow/ai_flow/test/project.yaml
Clear _default_ai_graph after workflow is generated
- Clear _default_ai_graph after workflow is generated
- Avoid submit a empty ai_graph
- ai_flow.test.api.test_airflow_job.TestAirflowProject.test_submit_twice_in_row
- ai_flow.test.api.test_airflow_job.TestAirflowProject.test_submit_empty_graph
> [AIFlow][Refactor] Clear _default_ai_graph after workflow is generated

- flink-ai-flow/ai_flow/java/client/pom.xml
- flink-ai-flow/ai_flow/java/pom.xml
- flink-ai-flow/lib/notification_service/java/pom.xml
The GRPC dependencies are shaded in Notification Service client, but the class names in META-INF/services don't relocate. The class names in META-INF/services for GRPC dependencies should be relocated through `org.apache.maven.plugins.shade.resource.ServicesResourceTransformer` in `maven-shade-plugin`.
> [Flink AI Flow] Notification client maven relocate META-INF/services

- flink-ai-flow/ai_flow/api/ops.py
- flink-ai-flow/lib/airflow/airflow/cli/cli_parser.py
- flink-ai-flow/lib/airflow/airflow/cli/commands/task_command.py
- flink-ai-flow/lib/airflow/airflow/contrib/jobs/dagrun_event_manager.py
- flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
- flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
- flink-ai-flow/lib/airflow/airflow/executors/base_executor.py
- flink-ai-flow/lib/airflow/airflow/jobs/local_task_job.py
- flink-ai-flow/lib/airflow/airflow/models/taskinstance.py
- flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
- flink-ai-flow/lib/airflow/tests/dags/test_event_handler.py
- flink-ai-flow/lib/airflow/tests/dags/test_schedule_with_task_status_change.py
- flink-ai-flow/lib/airflow/tests/events/test_scheduler_events.py
Airflow support scheduling base on TASK_STATUS_CHANGE event
- Send TASK_STATUS_CHANGE event when airflow task state is changed
- Use EventHandlerManager to handle TASK_STATUS_CHANGE
> [AIFlow] Airflow support scheduling base on TASK_STATUS_CHANGE event

- flink-ai-flow/docs/conf.py
Show scheduler interface on doc website as some Admin API documents refers to classes in this module.
We will need to update scheduler_plugin's python comments later as well.
> [Flink AI Flow] [Document] Show scheduler interface on doc website

- flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_plugin.py
Fix flink plugin bug when not using resources folder
Add `tab` to fix flink plugin bug when not using resources folder
> [Flink AI Flow] [bug fix] Fix flink plugin bug when not using resources folder

- flink-ai-flow/ai_flow/api/workflow_operation.py
- flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.py
*Current `submit_workflow` operation doesn't check the parameter `workflow_name`, which may cause that the name of the workflow submitted is different from the workflow name of the current workflow config.*
- *Add the check for the submit_workflow` operation to verify whether the name of the workflow submitted is same as the workflow name of the current workflow config.*
> [Flink AI Flow][API] Add the check for the workflow submission

- flink-ai-flow/ai_flow/scheduler_service/service/service.py
- flink-ai-flow/ai_flow/test/scheduler/test_scheduler_service.py
…_execution_on_event
Create workflow default context when workflow start/stop_new_execution_on_event
- Create workflow default context when workflow start/stop_new_execution_on_event
> [AIFlow] Create workflow default context when workflow start/stop_new_execution_on_event

- flink-ai-flow/lib/airflow/airflow/www/static/js/task-instances.js
- flink-ai-flow/lib/airflow/airflow/www/views.py
*The `DagRun` model adds the `context` column, which should add the column display in the frontend for Airflow.*
- *The tool tip of the tree view adds the `context` column content.*
> [Airflow][Frontend] Frontend introduces the context of the dag run

- flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
- flink-ai-flow/lib/airflow/airflow/models/baseoperator.py
- flink-ai-flow/lib/airflow/airflow/models/dag.py
- flink-ai-flow/lib/airflow/airflow/models/dagrun.py
- flink-ai-flow/lib/airflow/airflow/serialization/serialized_objects.py
- flink-ai-flow/lib/airflow/tests/models/test_baseoperator.py
A dag should be long-running only if it has a task that runs periodically or is subscribing to external events.
- Update the logic to determine long-running dag
- Fix the deserialization of BaseOperator
> [Airflow] Update the logic to determine long running dag

- flink-ai-flow/ai_flow/store/db/db_model.py
Use LargeBinary to fix import issue in doc website
- In db_model.py, use `LargeBinary` type to replace `Binary` type in sqlalchemy import as `Binary` will be deprecated.
> [Flink AI Flow] [Document] Use LargeBinary to fix import issue in doc website

- flink-ai-flow/ai_flow_plugins/job_plugins/bash/bash_job_plugin.py
Bash job controller set workflow execution context to environment variables.
- Bash job controller set workflow execution context to environment variables.
Manually tested.
> [AIFlow] Bash job controller set workflow execution context to env var

- flink-ai-flow/ai_flow/scheduler_service/service/workflow_event_processor.py
- flink-ai-flow/ai_flow/test/scheduler_service/service/test_workflow_event_processor.py
Skip events from default namespace in workflow_event_processor
- Skip events from `default` namespace in workflow_event_processor. Because there are no context extractor under this name. This keyword is preserved for external events like MODEL_GENERATED. Such events should not be handled by workflow_event_processor.
> [Flink AI Flow] Skip events from default namespace in workflow_event_processor

- flink-ai-flow/ai_flow_plugins/job_plugins/flink/__init__.py
- flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_env.py
- flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_run_main.py
- flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_wrapped_env.py
- flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.py
- flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink_processor.py
- flink-ai-flow/examples/wide_and_deep/workflows/wdl/cencus_stream_train_executors.py
To fix the bug related to flink_run_main.py & FlinkPythonProcessor mentioned in https://github.com/alibaba/flink-ai-extended/issues/475
- add ai_flow_plugins/job_plugins/flink/flink_wrapped_env.py
-  introduce WrappedBatchTableEnvironment, WrappedStreamTableEnvironment, WrappedStatementSet, which
- use wrapped class to **collect execution information when calling add_insert_sql and/or execute_sql**
- replace original class by wrapped class in flink_run_main.py & flink_env.py
- will write multiple job ids to ./job_id instead of single job id
(WIP: adding a branch to build flink&hive environment and test workflow which caused bug)
Integration test with flink & hive cluster in an external repo & branch: …
> [Flink AI Flow][Plugins] Introduce WrappedTableEnvironment and WrappedStatementSet in Flink job plugin

- flink-ai-flow/ai_flow_plugins/job_plugins/flink/read_only_flink/__init__.py
- flink-ai-flow/ai_flow_plugins/job_plugins/flink/read_only_flink/read_only_flink_job_plugin.py
- flink-ai-flow/ai_flow_plugins/job_plugins/flink/read_only_flink/read_only_flink_processor.py
- flink-ai-flow/ai_flow_plugins/job_plugins/read_only/__init__.py
- flink-ai-flow/ai_flow_plugins/job_plugins/read_only/read_only_job_plugin.py
- flink-ai-flow/ai_flow_plugins/job_plugins/read_only/read_only_processor.py
- flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/ai_flow_operator.py
- flink-ai-flow/ai_flow_plugins/tests/job_plugins/flink/read_only_flink/test_read_only_flink_job_plugin.py
- flink-ai-flow/ai_flow_plugins/tests/job_plugins/read_only/test_read_only_job_plugin.py
- flink-ai-flow/examples/demo/workflows/read_only_flink_workflow/read_only_flink_workflow.py
- flink-ai-flow/examples/demo/workflows/read_only_flink_workflow/read_only_flink_workflow.yaml
Add a read-only job plugin to allow users to add a job to the workflow without actually submit or stop the job.
We also implement a read-only flink job to show how to extend the read-only job to report runtime information of a read-only job.
- Add read-only job plugin
- Add read-only Flink job plugin
> [AIFlow] Add read-only job plugin

- flink-ai-flow/ai_flow/test/endpoint/test_high_availability.py
The AIFlow server HA test is unstable. And we will re-design and re-implement the HA of the AIFlow server, so we will skip HA test for now, and enable it after we re-implemented the HA.
- Skip AIFlow server HA test
> [AIFlow] Skip AIFlow server HA test

- flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_plugin.py
- flink-ai-flow/ai_flow_plugins/job_plugins/python/python_job_plugin.py
- flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/ai_flow_operator.py
- flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/test_ai_flow_operator.py
This pr is to avoid infinite loop when stopping flink job and python job. When the main python thread calls Popen.wait, it will grab a lock _waitpid_lock. If the process receives a signal and the signal handler call the stop method in the job plugin. It falls in an infinite loop, as the Popen.poll method will always return None if it cannot grab the lock _waitpid_lock. 
Therefore, we call Popen.poll in loop instead of Popen.wait.
- Avoid infinite loop when stopping flink job and python job
Manually verified.
> [AIFlow] Avoid infinite loop when stopping flink job and python job

- flink-ai-flow/ai_flow/java/client/pom.xml
- flink-ai-flow/ai_flow/java/pom.xml
- flink-ai-flow/lib/notification_service/java/pom.xml
Set AIFlow and Notification java client version to 0.2-SNAPSHOT
Set AIFlow and Notification java client version to 0.2-SNAPSHOT
> [AIFlow] Set AIFlow and Notification java client version to 0.2-SNAPSHOT

- flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/dag_generator.py
- flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.py
- flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.yaml
1. When using AirFlow scheduler, AI Flow jobs can be configured with airflow operator parameters.
> [AI Flow]AI Flow jobs can be configured with airflow operator parameters

- flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
Start listen events before starting local executor
Start listen events before starting local executor
Manually verified.
> [AIFlow] Start listen events before starting local executor

- flink-ai-flow/ai_flow/model_center/service/service.py
- flink-ai-flow/ai_flow/scheduler_service/service/workflow_event_manager.py
- flink-ai-flow/ai_flow/test/api/ut_workflows/workflows/test_ai_flow_context/test_ai_flow_context.py
- flink-ai-flow/ai_flow/test/api/ut_workflows/workflows/test_ops/test_ops.py
- flink-ai-flow/ai_flow/test/scheduler_service/service/test_workflow_event_manager.py
- flink-ai-flow/lib/airflow/airflow/jobs/local_task_job.py
- flink-ai-flow/lib/airflow/airflow/operators/subdag.py
- flink-ai-flow/lib/notification_service/java/src/main/java/org/aiflow/notification/conf/Configuration.java
- flink-ai-flow/lib/notification_service/notification_service/client.py
Make notification client idempotence enabled by default
- Create notification client lazily in ModelCenterService and WorkflowEventManager
- Close notification clients those will be frequently created
- Make enable.idempotence True by default
> [Flink AI Flow] Make notification client idempotence enabled by default

- flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/dag_generator.py
- flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_python/test_python.yaml
1. Solve the bug that the workflow configuration contains single quotes and it is illegal to translate workflow into AirFlow dag file。
> [AI Flow]Solve the bug that the dag file is illegal

- flink-ml-framework/python/flink_ml_framework/version.py
- flink-ml-framework/python/setup.py
- flink-ml-tensorflow-2.x/python/flink_ml_tensorflow/version.py
- flink-ml-tensorflow-2.x/python/setup.py
- flink-ml-tensorflow/python/flink_ml_tensorflow/version.py
- flink-ml-tensorflow/python/setup.py
Standardize python package version
Standardize python package version
> Standardize python package version

- flink-ml-framework/src/main/java/org/flinkextended/flink/ml/util/FileUtil.java
- flink-ml-framework/src/main/java/org/flinkextended/flink/ml/util/PythonUtil.java
Use java lib to unzip files to avoid dependency on unzip command of the OS.
Use java lib to unzip file
> Use java lib to unzip file

- flink-ml-examples/pom.xml
- flink-ml-examples/src/test/java/org/flinkextended/flink/ml/examples/tensorflow/ut/TFRecordInputFormatTest.java
- flink-ml-tensorflow-common/src/main/java/org/flinkextended/flink/ml/tensorflow/io/TFRecordInputFormat.java
- flink-ml-tensorflow-common/src/main/java/org/flinkextended/flink/ml/tensorflow/io/TFRecordSource.java
*(For example: This pull request makes user can stop workflow externally.)*
- *Send StopDagEvent to Airflow scheduler via notification service*
- *Once received StopDagEvent, Airflow scheduler kills all running dag runs*
*(or)*
*(or)*
> fix org.apache.hadoop.conf.Configuration cannot set in the class

- .github/workflows/nightly-build.yaml
- tools/auditwheel
Tensorflow has a known [issue](https://github.com/tensorflow/tensorflow/issues/31807) of loading a manylinux2010 repaired custom ops. We need to whitelist tensorflow dependency for auditwheel making manylinux wheel so that the custom ops can be loaded properly.
- White list tensorflow dependency for auditwheel
- Test nightly build wheels in nightly workflow
Manually tested the github workflow.
> Whitelist tensorflow dependency for auditwheel making manylinux wheel

- doc/quick-start/quick_start_tensorflow_1.15.md
- doc/quick-start/quick_start_tensorflow_2.3.md
Remove extra space of commands in quick start
Remove extra space of commands in quick start
> Remove extra space of commands in quick start

- dl-on-flink-framework/src/test/java/org/flinkextended/flink/ml/cluster/rpc/AppMasterServerTest.java
Increase timeout waiting for AM in testing.
- Increase timeout waiting for AM in testing
> Increase timeout waiting for AM in testing

- doc/quick-start/quick_start_tensorflow_1.15.md
- doc/quick-start/quick_start_tensorflow_2.3.md
- tools/run_example.sh
Use the archive url to download flink binary to avoid breaking url.
Use the archive url to download flink binary.
> Use the archive url to download flink binary

- dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/ClusterConfig.java
- dl-on-flink-framework/src/test/java/org/flinkextended/flink/ml/cluster/ClusterConfigTest.java
- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/client/NodeUtils.java
NodeUtils set python path properties with entry file path at first so that the node can pick up the right entry file from MLContext.
- NodeUtils set python path properties with entry file path at first
> NodeUtils set python path properties with entry file path at first

- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/inputformat/AMInputFormat.java
- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/inputformat/AbstractNodeInputFormat.java
- dl-on-flink-operator/src/test/java/org/flinkextended/flink/ml/operator/ops/inputformat/AMInputFormatTest.java
AMInputFormat wait for am node finish before return from reachedEnd
AMInputFormat wait for am node finish before return from reachedEnd
> AMInputFormat wait for am node finish before return from reachedEnd

- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/coding/RowCSVCoding.java
- dl-on-flink-tensorflow-2.x/python/example/tensorflow_on_flink_table.py
- dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/test_tf_cluster_config.py
- dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/test_tf_utils.py
- dl-on-flink-tensorflow-common/src/main/java/org/flinkextended/flink/ml/tensorflow/client/TFClusterConfig.java
- dl-on-flink-tensorflow/python/example/tensorflow_on_flink_table.py
- dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_flink_ml_api.py
- dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_tf_cluster_config.py
- dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_tf_utils.py
- examples/tensorflow-on-flink/linear/flink_train.py
Use RowCSVCoding as TF default encoding/decoding class
Use RowCSVCoding as TF default encoding/decoding class
> Use RowCSVCoding as TF default encoding/decoding class

- .github/workflows/nightly-build.yaml
- .github/workflows/prepare-release.yaml
- README.md
- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/NodeOperator.java
- doc/quick-start/quick_start_pytorch.md
- doc/quick-start/quick_start_tensorflow_1.15.md
- doc/quick-start/quick_start_tensorflow_2.4.md
- examples/pytorch-on-flink/linear/flink_inference.py
- examples/pytorch-on-flink/linear/flink_train.py
- examples/pytorch-on-flink/linear/linear.py
- examples/tensorflow-on-flink/linear/flink_train.py
- examples/tensorflow-on-flink/linear/linear.py
- tools/run_example.sh
Update the quick start example for Tensorflow and Add a quick start example for PyTorch. Fix #728 
- Update the quick start example for Tensorflow to use the new API
- Add option to run iterative training for Tensorflow quick start
- Add PyTorch quick start example
> Update quick start examples

- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/NodeOperator.java
Avoid tight loop in NodeOperator#onEpochWatermarkIncremented
Avoid tight loop in NodeOperator#onEpochWatermarkIncremented
> Avoid tight loop in NodeOperator#onEpochWatermarkIncremented

- dl-on-flink-pytorch/python/dl_on_flink_pytorch/flink_ml/pytorch_estimator.py
- dl-on-flink-pytorch/python/tests/dl_on_flink_pytorch/flink_ml/test_pytorch_estimator.py
- dl-on-flink-tensorflow-2.x/python/dl_on_flink_tensorflow/flink_ml/tf_estimator.py
- dl-on-flink-tensorflow/python/dl_on_flink_tensorflow/flink_ml/tf_estimator.py
Support adding extra cluster config properties to estimator.
- Support adding extra cluster config properties to estimator.
> Support adding extra cluster config properties to estimator

- dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/rpc/NodeServer.java
- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/inputformat/AbstractNodeInputFormat.java
- dl-on-flink-operator/src/test/java/org/flinkextended/flink/ml/operator/ops/inputformat/AbstractNodeInputFormatTest.java
- dl-on-flink-pytorch/src/test/java/org/flinkextended/flink/ml/pytorch/FailOverTest.java
- dl-on-flink-pytorch/src/test/resources/always_fail.py
- dl-on-flink-tensorflow-2.x/src/test/java/org/flinkextended/flink/ml/tensorflow/client/RunWithFailTest.java
- dl-on-flink-tensorflow-2.x/src/test/resources/always_fail.py
- dl-on-flink-tensorflow/src/test/java/org/flinkextended/flink/ml/tensorflow/client/RunWithFailTest.java
- dl-on-flink-tensorflow/src/test/resources/always_fail.py
The `AbstractNodeInputFormat` is closed when the node server failover, which is not intended. We update the `AbstractNodeInputFormat` so that it only close when the node server finishes.
Fix unstable failover test
> Fix unstable failover test

- dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/node/runner/CommonMLRunner.java
- dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/node/runner/NodeHeartBeatRunner.java
- dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/rpc/NodeServer.java
- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/NodeOperator.java
- dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/inputformat/AbstractNodeInputFormat.java
- dl-on-flink-operator/src/test/java/org/flinkextended/flink/ml/operator/ops/NodeOperatorTest.java
- dl-on-flink-operator/src/test/java/org/flinkextended/flink/ml/operator/ops/inputformat/AbstractNodeInputFormatTest.java
NodeServer#stopMLRunner should not swallow the InterruptedException
NodeServer#stopMLRunner should not swallow the InterruptedException
> NodeServer#stopMLRunner should not swallow the InterruptedException
