flink-extended/dl-on-flink

README.md
flink-ml-examples/pom.xml
flink-ml-examples/src/test/java/com/alibaba/flink/ml/examples/pytorch/it/PyTorchUtilIT.java
flink-ml-examples/src/test/java/com/alibaba/flink/ml/examples/tensorflow/it/FailoverIT.java
flink-ml-examples/src/test/java/com/alibaba/flink/ml/examples/tensorflow/it/JavaInferenceFailoverIT.java
flink-ml-examples/src/test/java/com/alibaba/flink/ml/examples/tensorflow/it/MnistIT.java
flink-ml-examples/src/test/java/com/alibaba/flink/ml/examples/wordcount/it/WordCountIT.java
flink-ml-framework/pom.xml
flink-ml-framework/python/setup.py
flink-ml-framework/src/main/java/com/alibaba/flink/ml/cluster/rpc/AppMasterServer.java
flink-ml-framework/src/main/java/com/alibaba/flink/ml/util/SysUtil.java
flink-ml-framework/src/test/java/com/alibaba/flink/ml/cluster/AppMasterServerTest.java
flink-ml-framework/src/test/java/com/alibaba/flink/ml/util/SysUtilTest.java
flink-ml-operator/pom.xml
flink-ml-pytorch/pom.xml
flink-ml-tensorflow/pom.xml
flink-ml-tensorflow/python/setup.py
pom.xml

now master version is 1.0, change version to 0.1.0

change project version to 0.1.0

---

README.md
flink-ml-examples/pom.xml
flink-ml-framework/pom.xml
flink-ml-framework/src/test/java/com/alibaba/flink/ml/util/SysUtilTest.java
flink-ml-operator/pom.xml
flink-ml-pytorch/pom.xml
flink-ml-tensorflow/pom.xml
pom.xml

change project version to 0.1.0

[release]version 0.1.0

---

flink-ml-tensorflow/python/cmake/modules/FindTensorFlow.cmake
flink-ml-tensorflow/python/flink_ml_tensorflow/ops/flink_writer_ops.cc
flink-ml-tensorflow/python/flink_ml_tensorflow/ops/queue_file_system.cc
flink-ml-tensorflow/python/setup.py
flink-ml-tensorflow/src/main/java/com/alibaba/flink/ml/tensorflow/coding/ExampleCoding.java
pom.xml
user.properties

Upgrade the tensorflow's version to 1.13.1

[enhancement]upgrade tf version to 1.13.1

---

README.md
docker/flink/Dockerfile
flink-ml-examples/pom.xml
flink-ml-examples/src/test/java/com/alibaba/flink/ml/examples/tensorflow/ut/TFMnistInferenceTest.java
flink-ml-framework/pom.xml
flink-ml-framework/python/setup.py
flink-ml-framework/src/test/java/com/alibaba/flink/ml/util/SysUtilTest.java
flink-ml-lib/pom.xml
flink-ml-operator/pom.xml
flink-ml-operator/src/main/java/com/alibaba/flink/ml/operator/ops/inputformat/MLInputFormat.java
flink-ml-operator/src/test/java/com/alibaba/flink/ml/operator/client/TableTestUtil.java
flink-ml-pytorch/pom.xml
flink-ml-tensorflow/pom.xml
flink-ml-tensorflow/python/setup.py
flink-ml-tensorflow/src/main/java/com/alibaba/flink/ml/tensorflow/client/TFUtils.java
flink-ml-tensorflow/src/test/java/com/alibaba/flink/ml/tensorflow/client/RunWithFailTest.java
flink-ml-tensorflow/src/test/java/com/alibaba/flink/ml/tensorflow/client/TFUtilsTest.java
pom.xml

Branch 0.2.0

---

flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/client/NotificationClient.java
flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/proto/NotificationServiceGrpc.java
flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/proto/NotificationServiceOuterClass.java
flink-ai-flow/lib/notification_service/java/src/test/java/com/aiflow/notification/client/NotificationClientTest.java
flink-ai-flow/lib/notification_service/java/src/test/java/com/aiflow/notification/service/LocalNotificationService.java
flink-ai-flow/lib/notification_service/notification_service/base_notification.py
flink-ai-flow/lib/notification_service/notification_service/client.py
flink-ai-flow/lib/notification_service/notification_service/event_storage.py
flink-ai-flow/lib/notification_service/notification_service/mongo_event_storage.py
flink-ai-flow/lib/notification_service/notification_service/mongo_notification.py
flink-ai-flow/lib/notification_service/notification_service/proto/notification_service.proto
flink-ai-flow/lib/notification_service/notification_service/proto/notification_service_pb2.py
flink-ai-flow/lib/notification_service/notification_service/proto/notification_service_pb2_grpc.py
flink-ai-flow/lib/notification_service/notification_service/service.py
flink-ai-flow/lib/notification_service/tests/test_mongo_notification.py

#90 
1. support mongodb
2. add getLatestVersionByKey api in service

feature(client&service):

---

flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/proto/NotificationServiceGrpc.java
flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/proto/NotificationServiceOuterClass.java
flink-ai-flow/lib/notification_service/notification_service/base_notification.py
flink-ai-flow/lib/notification_service/notification_service/client.py
flink-ai-flow/lib/notification_service/notification_service/event_storage.py
flink-ai-flow/lib/notification_service/notification_service/high_availability.py
flink-ai-flow/lib/notification_service/notification_service/master.py
flink-ai-flow/lib/notification_service/notification_service/proto/notification_service.proto
flink-ai-flow/lib/notification_service/notification_service/proto/notification_service_pb2.py
flink-ai-flow/lib/notification_service/notification_service/proto/notification_service_pb2_grpc.py
flink-ai-flow/lib/notification_service/notification_service/service.py
flink-ai-flow/lib/notification_service/notification_service/util/db.py
flink-ai-flow/lib/notification_service/notification_service/util/utils.py
flink-ai-flow/lib/notification_service/tests/test_high_availability.py
flink-ai-flow/lib/notification_service/tests/test_notification.py

notification service support high availability.

notification service support high availability.

---

flink-ai-flow/ai_flow/store/db/db_model.py

fix(store): revise sqla relationship param into reasonable names

---

flink-ai-flow/ai_flow/common/configuration.py
flink-ai-flow/ai_flow/common/yaml_utils.py

https://github.com/alibaba/flink-ai-extended/issues/108

fix(config): fix deprecated yaml.load warning

---

flink-ai-flow/lib/airflow/airflow/migrations/versions/e3a246e0dc1_current_schema.py

fix the quickstart.md failure caused by the outdated event_model definition.

fix the quickstart.md failure

---

flink-ai-flow/ai_flow/store/sqlalchemy_store.py
flink-ai-flow/ai_flow/test/store/common.py

Fix get_latest_validated_model_version and get_latest_generated_model_version

---

flink-ai-flow/QUICKSTART.md
flink-ai-flow/ai_flow/graph/edge.py

Add troubleshooting section to help users use the project.

Fix bug in Edge class and refine Quickstart document

---

flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/client/AIFlowClient.java
flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/client/EventListener.java
flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/client/NotificationClient.java
flink-ai-flow/lib/notification_service/java/src/test/java/com/aiflow/notification/client/NotificationClientTest.java
flink-ai-flow/lib/notification_service/notification_service/client.py

Currently notification client doesn't support to specify the user-defined namespace. Methods of notification client should support to add namespace parameter.

notification client add namespace

---

flink-ai-flow/lib/notification_service/java/src/main/java/com/aiflow/notification/client/NotificationClient.java

[#147 ](https://github.com/alibaba/flink-ai-extended/issues/147)
check `enableha` variable while initialize `notificationServiceStub`.

Fix notification service proto code issues and notification java client issue

---

flink-ai-flow/ai_flow/airflow/dag_generator.py
flink-ai-flow/ai_flow/api/ops.py
flink-ai-flow/ai_flow/graph/edge.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/dag_trigger.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/dagrun_event_manager.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_handlers.py
flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
flink-ai-flow/lib/airflow/airflow/executors/base_executor.py
flink-ai-flow/lib/airflow/airflow/executors/scheduling_action.py
flink-ai-flow/lib/airflow/airflow/migrations/versions/d47076ca1426_add_event_based_scheduler_support.py
flink-ai-flow/lib/airflow/airflow/models/baseoperator.py
flink-ai-flow/lib/airflow/airflow/models/dag.py
flink-ai-flow/lib/airflow/airflow/models/taskstate.py
flink-ai-flow/lib/airflow/airflow/serialization/serialized_objects.py
flink-ai-flow/lib/airflow/airflow/utils/dag_processing.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_dag_trigger.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_task_event_manager.py
flink-ai-flow/lib/airflow/tests/dags/test_event_task_dag.py
flink-ai-flow/lib/airflow/tests/dags/test_single_task_dag.py
flink-ai-flow/lib/airflow/tests/events/__init__.py
flink-ai-flow/lib/airflow/tests/events/test_scheduler_events.py
flink-ai-flow/lib/airflow/tests/models/test_dag.py
flink-ai-flow/lib/airflow/tests/models/test_taskstate.py
flink-ai-flow/lib/airflow/tests/serialization/test_dag_serialization.py
flink-ai-flow/pom.xml

Make event driven dag example pass.

[Airflow2.0]Add event driven dag example

---

flink-ai-flow/ai_flow/airflow/dag_generator.py
flink-ai-flow/ai_flow/plugins/local_cmd_job_plugin.py
flink-ai-flow/ai_flow/rest_endpoint/protobuf/proto/gen_protobuf.sh
flink-ai-flow/ai_flow/test/airflow/test_dag_generator.py
flink-ai-flow/flink_ai_flow/kubernetes_flink_job.py
flink-ai-flow/flink_ai_flow/local_flink_job.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_handlers.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/airflow/tests/dags/test_aiflow_dag.py
flink-ai-flow/lib/airflow/tests/serialization/test_dag_serialization.py
flink-ai-flow/python_ai_flow/kubernetes_python_job.py
flink-ai-flow/python_ai_flow/local_python_job.py
flink-ai-flow/requirements.txt

Add a test which 's dag generated by Flink AI Flow.

[Airflow2.0]Add Flink ai flow  workflow test

---

flink-ai-flow/lib/airflow/airflow/contrib/jobs/dag_trigger.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/scheduler_client.py
flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
flink-ai-flow/lib/airflow/airflow/utils/dag_processing.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_dag_trigger.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/notification_service/notification_service/base_notification.py
flink-ai-flow/lib/notification_service/notification_service/event_storage.py
flink-ai-flow/lib/notification_service/notification_service/mongo_notification.py
flink-ai-flow/lib/notification_service/notification_service/util/db.py
flink-ai-flow/lib/notification_service/setup.py
flink-ai-flow/lib/notification_service/tests/test_notification.py

Add user trigger parse dag execution.

Add user trigger parse dag execution.

---

flink-ai-flow/ai_flow/airflow/dag_generator.py
flink-ai-flow/ai_flow/api/execution.py
flink-ai-flow/ai_flow/api/project.py
flink-ai-flow/ai_flow/plugins/local_cmd_job_plugin.py
flink-ai-flow/ai_flow/project/project_config.py
flink-ai-flow/ai_flow/test/api/test_project.py
flink-ai-flow/ai_flow/test/project.yaml
flink-ai-flow/ai_flow/test/test_util.py
flink-ai-flow/ai_flow/test/workflow_config.yaml
flink-ai-flow/ai_flow/workflow/workflow_config.py
flink-ai-flow/flink_ai_flow/kubernetes_flink_job.py
flink-ai-flow/flink_ai_flow/local_flink_job.py
flink-ai-flow/lib/airflow/airflow/utils/dag_processing.py
flink-ai-flow/python_ai_flow/kubernetes_python_job.py
flink-ai-flow/python_ai_flow/local_python_job.py

merge parse_dag and trigger dag to  flink aiflow run interface

refactor api

---

flink-ai-flow/ai_flow/airflow/dag_generator.py
flink-ai-flow/ai_flow/api/project.py
flink-ai-flow/ai_flow/test/airflow/test_dag_generator.py
flink-ai-flow/ai_flow/test/api/test_airflow_job.py
flink-ai-flow/ai_flow/test/api/test_project.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/utils/dag_processing.py

Refactor test and add some log

add some log

---

flink-ai-flow/ai_flow/bin/start-aiflow.sh
flink-ai-flow/entrypoint.sh

Adjust order of creating user for airflow to fix database issue.

Fix Start Shellscript

---

flink-ai-flow/examples/README.md
flink-ai-flow/examples/python_examples/python_codes/batch_train_batch_predict_airflow/batch_train_batch_predict_executor.py
flink-ai-flow/examples/python_examples/python_codes/batch_train_batch_predict_airflow/sklearn_batch_train_batch_predict.py

1. To run this example in docker, make sure the memory of the docker container is >= 4GB

Add batch train batch predict example with AirFlow

---

flink-ai-flow/ai_flow/airflow/dag_generator.py
flink-ai-flow/ai_flow/test/airflow/test_dag_generator.py
flink-ai-flow/ai_flow/workflow/job_config.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/periodic_manager.py
flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
flink-ai-flow/lib/airflow/airflow/models/dagrun.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/airflow/tests/dags/test_periodic_task_dag.py
flink-ai-flow/lib/airflow/tests/test_utils/db.py

[AirFlow] Add periodic task support.

Add periodic task support

---

flink-ai-flow/QUICKSTART.md
flink-ai-flow/ai_flow/bin/install_aiflow.sh

1. Improve stop-aiflow.sh
2. Add install script

Improve QuickStart by adding install script

---

flink-ai-flow/ai_flow/api/execution.py
flink-ai-flow/build_mini_sdist_package.sh
flink-ai-flow/build_mini_whl_package.sh
flink-ai-flow/requirements-mini.txt
flink-ai-flow/setup-mini.py

Currently Flink AI Flow wheel package includes Airflow, Notification Service etc, which couldn't friendly support different Python versions. Flink AI Flow could provide users with mini wheel package including AI Flow and Notification Service.

build mini wheel package

---

flink-ai-flow/lib/airflow/airflow/cli/cli_parser.py
flink-ai-flow/lib/airflow/airflow/cli/commands/webserver_command.py
flink-ai-flow/lib/airflow/airflow/www/app.py
flink-ai-flow/lib/airflow/airflow/www/extensions/init_views.py
flink-ai-flow/lib/airflow/airflow/www/views.py

Airflow WebUI currently couldn't trigger dag/task schedule, which could be trigger manually.

frontend trigger dag/task schedule

---

flink-ai-flow/examples/python_examples/sklearn_batch_train_stream_predict/project.yaml
flink-ai-flow/examples/python_examples/sklearn_batch_train_stream_predict/python_codes/batch_train_stream_predict_executor.py
flink-ai-flow/examples/python_examples/sklearn_batch_train_stream_predict/python_codes/sklearn_batch_train_stream_predict.py
flink-ai-flow/examples/python_examples/sklearn_batch_train_stream_predict/resources/workflow_config.yaml
flink-ai-flow/examples/python_examples/sklearn_stream_train_batch_predict/project.yaml
flink-ai-flow/examples/python_examples/sklearn_stream_train_batch_predict/python_codes/sklearn_stream_train_batch_predict.py
flink-ai-flow/examples/python_examples/sklearn_stream_train_batch_predict/python_codes/stream_train_batch_predict_executor.py
flink-ai-flow/examples/python_examples/sklearn_stream_train_batch_predict/resources/workflow_config.yaml

Add batch train stream predict and stream train batch predict examples
- Add batch train and stream predict example using sklearn on local machine. 
- the batch train job is a periodic job
- Add stream train and batch predict example using sklearn on local machine. 
This change is already covered by existing tests.

Add batch train stream predict and stream train batch predict examples

---

flink-ai-flow/requirements.txt

Update Kafka package in requirement list
- use `kafka-python` instead of `kafka`
This change is already covered by existing tests, e.g. wide and deep demo.

[bugfix][Flink-AI-Flow] Update Kafka package in requirement list

---

flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/executors/base_executor.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/airflow/tests/dags/test_multiple_trigger_task_dag.py

Make sure that only one task(the same task_id) is running at the same time.

Make sure that only one task is running at the same time.

---

flink-ai-flow/ai_flow/test/api/test_af_context.py
flink-ai-flow/ai_flow/test/api/workflow.yaml
flink-ai-flow/ai_flow/test/translator/test_base_translator.py
flink-ai-flow/ai_flow/translator/base_translator.py

Check periodic job is validated. If a job has periodic config, it can not have upstream jobs.

Check periodic job is validated

---

flink-ai-flow/lib/airflow/airflow/utils/dag_processing.py

[AirFlow] Fix parse dag dead lock bug.

---

flink-ai-flow/lib/airflow/airflow/www/templates/airflow/dag.html
flink-ai-flow/lib/airflow/airflow/www/templates/airflow/graph.html
flink-ai-flow/lib/airflow/airflow/www/views.py

Airflow UI should support show the event count of event senders.

frontend send events

---

flink-ai-flow/lib/airflow/airflow/www/static/js/events.js
flink-ai-flow/lib/airflow/airflow/www/templates/airflow/graph.html
flink-ai-flow/lib/airflow/airflow/www/views.py

Airflow UI doesn't support dynamic dependency for Graph or Tree View, therefore the frontend should support to show the dynamic dependency based on the senders of events.

frontent dynamic dependency

---

flink-ai-flow/lib/airflow/airflow/www/views.py

Airflow UI shouldn't show the edges between sender and event, which should be showed based on the event records sent.

frontend event sender

---

flink-ai-flow/lib/airflow/airflow/www/views.py

AirFlow UI should support static dependencies which is based on sender for subscribe_events method, and dynamic dependencies which is based on event records sent.

frontend static dependency

---

flink-ai-flow/lib/airflow/airflow/www/static/js/task-instances.js
flink-ai-flow/lib/airflow/airflow/www/views.py

Airflow UI doesn't support show periodic task, which should show the periodic task for event based scheduler in frontend.

frontend periodic task

---

flink-ai-flow/ai_flow/client/__init__.py
flink-ai-flow/ai_flow/endpoint/client/metadata_client.py
flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/client/AIFlowClient.java
flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/client/MetadataClient.java
flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/proto/MetadataServiceOuterClass.java
flink-ai-flow/ai_flow/metadata_store/service/service.py
flink-ai-flow/ai_flow/protobuf/metadata_service_pb2.py
flink-ai-flow/ai_flow/protobuf/proto/gen_protobuf.sh
flink-ai-flow/ai_flow/protobuf/proto/metadata_service.proto
flink-ai-flow/ai_flow/store/abstract_store.py
flink-ai-flow/ai_flow/store/mongo_store.py
flink-ai-flow/ai_flow/store/sqlalchemy_store.py
flink-ai-flow/ai_flow/test/endpoint/test_client.py
flink-ai-flow/ai_flow/test/store/common.py

Remove create_time and update_time from register and update dataset operation
- Remove create_time and update_time from client parameters
- Remove deploy_service from gen_protobuf script
This change is already covered by existing tests.

[Flink AI Flow] Remove create_time and update_time from register and update dataset operation

---

flink-ai-flow/ai_flow/graph/ai_nodes/dataset.py

DataSet extends ExecutableNode
DataSet extends ExecutableNode

[AIFlow][Refactor] DataSet extends ExecutableNode

---

flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/periodic_manager.py
flink-ai-flow/lib/airflow/airflow/models/baseoperator.py
flink-ai-flow/lib/airflow/airflow/models/dag.py
flink-ai-flow/lib/airflow/airflow/models/dagrun.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_periodic_manager.py
flink-ai-flow/lib/airflow/tests/dags/test_periodic_cron_task_dag.py
flink-ai-flow/lib/airflow/tests/dags/test_periodic_interval_task_dag.py

1. Make task periodic expression same to cron table expression.
2. Dag with periodic task or subscribed event task is long running dag.

[AirFlow][refactor] change periodic expression and add long running dag

---

flink-ai-flow/ai_flow/test/workflow/test_workflow.py
flink-ai-flow/ai_flow/test/workflow/workflow_1.yaml
flink-ai-flow/ai_flow/workflow/workflow_config.py

The WorkflowConfig add job_periodic_config_dict field.
The WorkflowConfig add job_periodic_config_dict field.

[Flink AI Flow] [Refactor] Add Job's PeriodicConfig  to WorkflowConfig

---

flink-ai-flow/ai_flow_plugins/scheduler_plugins/__init__.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/__init__.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/ai_flow_operator.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/airflow_scheduler.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/dag_generator.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/event_handler.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/__init__.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/__init__.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/mock_scheduler_plugin.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/master.yaml
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/project.yaml
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.yaml
flink-ai-flow/run_tests.sh

1. Add AirFlow scheduler plugin.

[Flink AI Flow][plugins] Add AirFlow scheduler plugin

---

flink-ai-flow/ai_flow_plugins/job_plugins/python/__init__.py
flink-ai-flow/ai_flow_plugins/job_plugins/python/python_job_config.py
flink-ai-flow/ai_flow_plugins/job_plugins/python/python_job_plugin.py
flink-ai-flow/ai_flow_plugins/job_plugins/python/python_processor.py
flink-ai-flow/ai_flow_plugins/job_plugins/python/python_run_main.py
flink-ai-flow/ai_flow_plugins/job_plugins/utils/__init__.py
flink-ai-flow/ai_flow_plugins/job_plugins/utils/run_graph.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_python/__init__.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_python/test_python.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_python/test_python.yaml

[Flink AI Flow][plugin] Add python job plugin

---

flink-ai-flow/ai_flow/__init__.py
flink-ai-flow/ai_flow_plugins/tests/airflow_db_utils.py
flink-ai-flow/ai_flow_plugins/tests/airflow_scheduler_utils.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/master.yaml
flink-ai-flow/ai_flow_plugins/tests/it_workflows/project.yaml
flink-ai-flow/ai_flow_plugins/tests/it_workflows/resources/word_count.txt
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_action_on_event/__init__.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_action_on_event/test_action_on_event.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_action_on_event/test_action_on_event.yaml
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_bash/__init__.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_bash/test_bash.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_bash/test_bash.yaml
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_flink/__init__.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_flink/test_flink.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_flink/test_flink.yaml
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_periodic_job/__init__.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_periodic_job/test_periodic_job.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_periodic_job/test_periodic_job.yaml
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_periodic_workflow/__init__.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_periodic_workflow/test_periodic_workflow.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_python/__init__.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_python/test_python.py
flink-ai-flow/ai_flow_plugins/tests/it_workflows/workflows/test_python/test_python.yaml
flink-ai-flow/pom.xml

1. Add IT case
2. Export EventCondition

[Flink AI Flow] Add IT case

---

.github/workflows/flink_ai_flow_ci.yml
flink-ai-flow/ai_flow/java/client/pom.xml
flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/client/AIFlowClient.java
flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/client/MetadataClient.java
flink-ai-flow/ai_flow/java/client/src/main/java/com/aiflow/entity/WorkflowMeta.java
flink-ai-flow/ai_flow/java/client/src/test/java/com/aiflow/client/AIFlowClientTest.java
flink-ai-flow/ai_flow/java/client/src/test/java/com/aiflow/client/SingleJUnitTestRunner.java
flink-ai-flow/ai_flow/java/client/src/test/resources/assembly.xml
flink-ai-flow/ai_flow/java/client/src/test/resources/test.properties
flink-ai-flow/ai_flow/java/pom.xml
flink-ai-flow/ai_flow/test/endpoint/test_java_client.py
flink-ai-flow/lib/notification_service/java/pom.xml
flink-ai-flow/pom.xml
flink-ai-flow/run_tests.sh

[Flink AI Flow] [Test] Add Java Client Unit Test

---

flink-ai-flow/ai_flow/api/ops.py

The comments of the API in `ops.py` don't follow the standard of the API document, which should be improved.
- *Update the comments of the API in `ops.py` to follow the standard of the API document.*

[Flink AI Flow][Document] Improve OPS API

---

flink-ai-flow/ai_flow/api/workflow_operation.py

The comments of the API in `workflow_operation.py` don't follow the standard of the API document, which should be improved.
- *Update the comments of the API in `workflow_operation.py` to follow the standard of the API document.*

[Flink AI Flow][Document] Improve Admin API 

---

flink-ai-flow/ai_flow_plugins/blob_manager_plugins/blob_manager_utils.py
flink-ai-flow/ai_flow_plugins/blob_manager_plugins/local_blob_manager.py
flink-ai-flow/ai_flow_plugins/blob_manager_plugins/oss_blob_manager.py
flink-ai-flow/ai_flow_plugins/tests/blob_manager_plugins/test_local_blob_manager.py

1. Solve the bug of downloading files at the same time.

[Flink AI Flow]Solve the bug of downloading files at the same time

---

flink-ai-flow/.dockerignore
flink-ai-flow/Dockerfile
flink-ai-flow/bin/start-aiflow.sh
flink-ai-flow/bin/start_aiflow.py
flink-ai-flow/examples/demo/project.yaml
flink-ai-flow/lib/airflow/airflow/config_templates/default_airflow.cfg

Fix start script for code refactor

[Flink AI Flow] Fix start script for code refactor

---

flink-ai-flow/ai_flow/api/ai_flow_context.py

1. Fix init_ai_flow_context bug.

[Flink AI Flow] Fix init_ai_flow_context bug

---

flink-ai-flow/bin/start_notification_service.py

Improve notification arg help docs
Improve notification arg help docs

[Notification] Improve notification arg help docs

---

flink-ai-flow/ai_flow/ai_graph/ai_graph.py
flink-ai-flow/ai_flow/ai_graph/ai_node.py
flink-ai-flow/ai_flow/ai_graph/data_edge.py

Refine documents of AI Graph package
This change is a trivial rework / code cleanup without any test coverage

[Flink AI Flow] [Document] Refine documents of AI Graph package

---

flink-ai-flow/ai_flow_plugins/job_plugins/flink/__init__.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_env.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_plugin.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.py

1. Support setting FlinkEnv separately for each flink job.

[Flink AI Flow] [Plugins]Support setting FlinkEnv separately for each flink job.

---

flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_config.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_plugin.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.yaml

flink job:
1. User can set stop_mode configuration.

[Flink AI Flow] User can set stop_mode configuration.

---

flink-ai-flow/bin/start-all-aiflow-services.sh

Wait for ns to reach the running state

[Flink AI Flow][bin] Wait for ns to reach the running state

---

.readthedocs.yaml
flink-ai-flow/docs/conf.py

*(For example: This pull request makes user can stop workflow externally.)*
- *Send StopDagEvent to Airflow scheduler via notification service*
- *Once received StopDagEvent, Airflow scheduler kills all running dag runs*
*(or)*
*(or)*

install yarn in doc env

---

flink-ai-flow/ai_flow/__init__.py
flink-ai-flow/ai_flow/api/ai_flow_context.py
flink-ai-flow/ai_flow/context/project_context.py
flink-ai-flow/ai_flow/project/project_config.py
flink-ai-flow/ai_flow/test/api/test_ai_flow_context.py
flink-ai-flow/ai_flow/test/project/project.yaml
flink-ai-flow/ai_flow/test/project/test_project_config.py

[Flink AI Flow]Add init_ai_client api

---

flink-ai-flow/ai_flow/frontend/static/.gitignore

*Flink AI Flow should support the workflow frontend of the AIFlow UI for the user-defined workflow display.*
- *Introduce the workflow frontend of the AIFlow UI*

[Flink AI Flow][Frontend] Introduce the workflow frontend of the AIFlow UI

---

flink-ai-flow/ai_flow/scheduler_service/service/workflow_event_processor.py
flink-ai-flow/ai_flow/test/scheduler_service/service/test_workflow_event_processor.py

Fix bug in WorkflowEventProcessor
- correct the code to use project name in WorkflowEventProcessor

[Flink AI Flow] Fix bug in WorkflowEventProcessor

---

flink-ai-flow/ai_flow/scheduler_service/service/workflow_event_processor.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/__init__.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_processor.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_wrapped_env.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.py
flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink_processor.py

Add FlinkSqlProcessor for #462
- Add FlinkSqlProcessor based on FlinkPythonProcessor to allow users to write sql only for defining a flink job.
- Add unit tests

[Flink AI Flow] Add FlinkSqlProcessor

---

flink-ai-flow/ai_flow_plugins/tests/job_plugins/ut_workflows/workflows/test_flink/test_flink.py

Fix ut of FlinkSqlProcessor
- Reset the flink env when running flink processor ut.

[Flink AI Flow] Fix ut of FlinkSqlProcessor

---

flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/test_event_handler.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/dagrun_event_manager.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/scheduler_client.py
flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
flink-ai-flow/lib/airflow/airflow/executors/base_executor.py
flink-ai-flow/lib/airflow/airflow/jobs/local_task_job.py
flink-ai-flow/lib/airflow/airflow/migrations/versions/c12f471f01f4_add_seq_num_to_task_instance.py
flink-ai-flow/lib/airflow/airflow/migrations/versions/d47076ca1426_add_event_based_scheduler_support.py
flink-ai-flow/lib/airflow/airflow/migrations/versions/e3a246e0dc1_current_schema.py
flink-ai-flow/lib/airflow/airflow/models/message.py
flink-ai-flow/lib/airflow/airflow/models/taskexecution.py
flink-ai-flow/lib/airflow/airflow/models/taskinstance.py
flink-ai-flow/lib/airflow/airflow/utils/log/file_task_handler.py
flink-ai-flow/lib/airflow/airflow/utils/mailbox.py
flink-ai-flow/lib/airflow/tests/contrib/jobs/test_event_based_scheduler.py
flink-ai-flow/lib/airflow/tests/dags/test_kill_task_retry_dag.py
flink-ai-flow/lib/airflow/tests/dags/test_task_retry_dag.py
flink-ai-flow/lib/airflow/tests/events/test_scheduler_events.py
flink-ai-flow/lib/airflow/tests/utils/test_mailbox.py

Add job retry mechanism

---

flink-ai-flow/lib/airflow/airflow/cli/commands/task_command.py
flink-ai-flow/lib/airflow/airflow/contrib/jobs/event_based_scheduler_job.py
flink-ai-flow/lib/airflow/airflow/events/scheduler_events.py
flink-ai-flow/lib/airflow/airflow/models/taskinstance.py
flink-ai-flow/lib/airflow/airflow/operators/subdag.py
flink-ai-flow/lib/airflow/airflow/task/task_runner/base_task_runner.py
flink-ai-flow/lib/airflow/tests/operators/test_subdag_operator.py

Fix compatibility about subdag
- Fix compatibility about subdag

[Flink AI Flow] [Airflow] Fix compatibility about subdag

---

flink-ai-flow/ai_flow/endpoint/server/server.py
flink-ai-flow/ai_flow/endpoint/server/web_server.py
flink-ai-flow/ai_flow/metadata_store/service/service.py
flink-ai-flow/ai_flow/model_center/service/service.py
flink-ai-flow/ai_flow/scheduler_service/service/service.py
flink-ai-flow/ai_flow/scheduler_service/service/workflow_event_manager.py
flink-ai-flow/ai_flow/store/db/db_util.py

Add util method to create db store
Add util method to create db store

[AIFlow] Add util method to create db store

---

flink-ai-flow/ai_flow/frontend/web_server.py
flink-ai-flow/bin/start_aiflow_web.py

Add option to config AIFlow web server host and port
Add option to config AIFlow web server host and port

[AIFlow] Add option to config AIFlow web server host and port

---

flink-ai-flow/lib/notification_service/setup.py
flink-ai-flow/pom.xml
flink-ai-flow/requirements.txt
flink-ai-flow/setup.py

1. Change version from 0.1 to 0.2

[AI Flow]Change version from 0.1 to 0.2

---

flink-ai-flow/lib/notification_service/bin/start_notification_service.py

…nabled
Allow user to set advertised server uri when HA enabled
- Add parameter --advertised-uri in start_notification_service.py

[Notification Service] Allow user to set advertised server uri when HA enabled

---

flink-ai-flow/ai_flow/endpoint/server/high_availability.py
flink-ai-flow/docker-compose.yaml
flink-ai-flow/lib/notification_service/notification_service/client.py
flink-ai-flow/lib/notification_service/notification_service/util/utils.py

Add docker compose using celery executor
- Check idempotence enabled after server uri checking
- Fix ValueError: sleep length must be non-negative 
- Add docker compose using celery executor

[Flink AI Flow] Add docker compose

---

flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/dag_generator.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.py

Fix DagGenerator not break line properly
Fix DagGenerator not break line properly

[AIFlow] Fix DagGenerator not break line properly

---

flink-ai-flow/ai_flow/frontend/.env
flink-ai-flow/ai_flow/frontend/.env.development
flink-ai-flow/ai_flow/frontend/.env.preview
flink-ai-flow/ai_flow/frontend/src/utils/request.js
flink-ai-flow/bin/start_aiflow_web.py
flink-ai-flow/chart/templates/NOTES.txt
flink-ai-flow/chart/templates/_helpers.yaml
flink-ai-flow/chart/templates/aiflow_webserver/webserver-deployment.yaml
flink-ai-flow/chart/templates/aiflow_webserver/webserver-ingress.yaml
flink-ai-flow/chart/templates/aiflow_webserver/webserver-networkpolicy.yaml
flink-ai-flow/chart/templates/aiflow_webserver/webserver-service.yaml
flink-ai-flow/chart/templates/aiflow_webserver/webserver-serviceaccount.yaml
flink-ai-flow/chart/values.schema.json
flink-ai-flow/chart/values.yaml

Add AIFlow webserver deployment to helm chart
Add AIFlow webserver deployment to helm chart
Manually test

[AIFlow][chart] Add AIFlow webserver deployment to helm chart

---

flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/airflow_scheduler.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/context_extractor.py
flink-ai-flow/ai_flow_plugins/scheduler_plugins/airflow/dag_generator.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/test_airflow_scheduler.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/test_context_extractor.py
flink-ai-flow/ai_flow_plugins/tests/scheduler_plugins/airflow/ut_workflows/workflows/test_dag_generator/test_dag_generator.py

Encode context extractor as base64 string in DAG file
Encode context extractor as base64 string in DAG file

[AIFlow] Encode context extractor as base64 string in DAG file

---

flink-ai-flow/lib/notification_service/tests/test_notification.py

[Notification Service] Make test_all_listen_events pass.

[Notification Service] Make test_all_listen_events pass.

---

flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_plugin.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_run_main.py

Fix Flink Job ID Serde.
- Store flink job ids into a file line by line(i.e. each line contains only 1 job id)
- Read job ids line by line when stopping a flink job

[Flink AI Flow] Fix Flink Job ID Serde

---

flink-ai-flow/chart/templates/aiflow_webserver/webserver-deployment.yaml

Mount airflow config to AIFlow web server
Mount airflow config to AIFlow web server

[AIFlow][chart] Mount airflow config to AIFlow web server

---

flink-ai-flow/chart/values.yaml
flink-ai-flow/docker-compose.yaml

*(For example: This pull request makes user can stop workflow externally.)*
- *Send StopDagEvent to Airflow scheduler via notification service*
- *Once received StopDagEvent, Airflow scheduler kills all running dag runs*
*(or)*
*(or)*

[Flink AI Flow] Modify docker image version

---

flink-ai-flow/ai_flow_plugins/job_plugins/bash/bash_job_config.py
flink-ai-flow/ai_flow_plugins/job_plugins/flink/flink_job_config.py
flink-ai-flow/ai_flow_plugins/job_plugins/python/python_job_config.py
flink-ai-flow/examples/wide_and_deep/workflows/wdl/cencus_stream_train_executors.py

Solve job config parsing error bug

[AI Flow Plugin] Solve job config parsing error bug.

---

pom.xml

Prepare jar release to maven central
Prepare jar release to maven central

Prepare jar release to maven central

---

flink-ml-tensorflow-2.x/python/setup.py
flink-ml-tensorflow/python/example/tensorflow_on_flink_table.py
flink-ml-tensorflow/python/flink_ml_tensorflow/tensorflow_TFConfig.py
flink-ml-tensorflow/python/flink_ml_tensorflow/tensorflow_on_flink_ml.py
flink-ml-tensorflow/python/flink_ml_tensorflow/tensorflow_on_flink_table.py
flink-ml-tensorflow/python/setup.py
flink-ml-tensorflow/python/tests/flink_ml_tensorflow/add_one.py
flink-ml-tensorflow/python/tests/flink_ml_tensorflow/test_flink_ml_api.py

flink-ml-tensorflow python support flink-ml api
flink-ml-tensorflow python support flink-ml api

flink-ml-tensorflow python support flink-ml api

---

flink-ml-framework/python/setup.py

Fix protobuf version conflict
Fix protobuf version conflict

Fix protobuf version conflict

---

.github/workflows/nightly-build.yaml

Nightly build upload flink-ml-dist bin package
Nightly build upload flink-ml-dist bin package

Nightly build upload flink-ml-dist bin package

---

flink-ml-tensorflow-2.x/pom.xml
flink-ml-tensorflow/pom.xml

flink-ml-tensorflow shade guava and apache commons library
flink-ml-tensorflow shade guava and apache commons library

flink-ml-tensorflow shade guava and apache commons library

---

flink-ml-dist/pom.xml
flink-ml-examples/pom.xml
flink-ml-framework/pom.xml
flink-ml-framework/python/flink_ml_framework/version.py
flink-ml-framework/src/test/java/org/flinkextended/flink/ml/util/SysUtilTest.java
flink-ml-lib/pom.xml
flink-ml-operator/pom.xml
flink-ml-pytorch/pom.xml
flink-ml-tensorflow-2.x/pom.xml
flink-ml-tensorflow-2.x/python/flink_ml_tensorflow/version.py
flink-ml-tensorflow-common/pom.xml
flink-ml-tensorflow/pom.xml
flink-ml-tensorflow/python/flink_ml_tensorflow/version.py
pom.xml

After cut the release-0.4 branch, we bump the version in the master branch.
Bump dl-on-flink version

Bump dl-on-flink version

---

README.md
doc/quick-start/quick_start_tensorflow_1.15.md
doc/quick-start/quick_start_tensorflow_2.3.md
doc/quick_start.md
examples/tensorflow-on-flink/linear/linear.py

Update quick start doc to provide better user experience
- Update quick start doc
- Update README

Update quick start doc

---

doc/quick-start/quick_start_tensorflow_1.15.md
doc/quick-start/quick_start_tensorflow_2.3.md

Recommend using virtualenv for quick start
Recommend using virtualenv for quick start

Recommend using virtualenv for quick start

---

.github/workflows/nightly-build.yaml
examples/tensorflow-on-flink/linear/linear.py
tools/run_example.sh

Run example in github action nighlty
- Add the step to run examples in nightly workflow
- Fix #706 

Run example in github action nighlty

---

.github/workflows/prepare-release.yaml

Add github workflow to prepare release
Add github workflow to prepare release

Add github workflow to prepare release

---

dl-on-flink-framework/src/test/java/org/flinkextended/flink/ml/cluster/rpc/AppMasterServerTest.java

Fix unstable unit test AppMasterServerTest#multiRegisterNode
fix #699 
Fix unstable unit test AppMasterServerTest#multiRegisterNode

Fix unstable unit test AppMasterServerTest#multiRegisterNode

---

.github/workflows/nightly-build.yaml
tools/run_example.sh

Install dev wheels for nightly build
- Install dev wheels for nightly build

Install dev wheels for nightly build

---

dl-on-flink-tensorflow-2.x/pom.xml
dl-on-flink-tensorflow-2.x/python/dl_on_flink_tensorflow/tf_cluster_config.py
dl-on-flink-tensorflow-2.x/python/dl_on_flink_tensorflow/tf_utils.py
dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/test_tf_cluster_config.py
dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/test_tf_utils.py
dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/utils.py
dl-on-flink-tensorflow/pom.xml
dl-on-flink-tensorflow/python/dl_on_flink_tensorflow/tf_cluster_config.py
dl-on-flink-tensorflow/python/dl_on_flink_tensorflow/tf_utils.py
dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_flink_ml_api.py
dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_tf_cluster_config.py
dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_tf_utils.py
dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/utils.py

Add Python TFUtils API
Add Python TFUtils API

Add Python TFUtils API

---

dl-on-flink-framework/python/dl_on_flink_framework/cluster_config.py
dl-on-flink-framework/python/test/test_cluster_config.py
dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/ClusterConfig.java
dl-on-flink-tensorflow-2.x/python/dl_on_flink_tensorflow/tf_cluster_config.py
dl-on-flink-tensorflow-2.x/python/dl_on_flink_tensorflow/tf_utils.py
dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/test_tf_cluster_config.py
dl-on-flink-tensorflow-2.x/python/tests/flink_ml_tensorflow/test_tf_utils.py
dl-on-flink-tensorflow-common/src/main/java/org/flinkextended/flink/ml/tensorflow/client/TFClusterConfig.java
dl-on-flink-tensorflow-common/src/main/java/org/flinkextended/flink/ml/tensorflow/client/TFUtils.java
dl-on-flink-tensorflow/python/dl_on_flink_tensorflow/tf_cluster_config.py
dl-on-flink-tensorflow/python/dl_on_flink_tensorflow/tf_utils.py
dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_tf_cluster_config.py
dl-on-flink-tensorflow/python/tests/flink_ml_tensorflow/test_tf_utils.py

Update DL on Flink Tensorflow Python API
- Update docstring
- Add cluster_config.py

Update DL on Flink Tensorflow Python API

---

README.md
dl-on-flink-tensorflow-2.x/pom.xml
dl-on-flink-tensorflow-2.x/python/setup.py
dl-on-flink-tensorflow-2.x/src/main/java/org/flinkextended/flink/ml/tensorflow/util/JavaInference.java
dl-on-flink-tensorflow-2.x/src/main/java/org/flinkextended/flink/ml/tensorflow/util/TFTensorConversion.java
dl-on-flink-tensorflow-2.x/src/test/java/org/flinkextended/flink/ml/tensorflow/util/TFTensorConversionTest.java
doc/quick-start/quick_start_tensorflow_2.4.md
tools/run_example.sh

Bump Supported Tensorflow version to 2.4.x
Bump Supported Tensorflow version to 2.4.x

Bump Supported Tensorflow version to 2.4.x

---

dl-on-flink-pytorch/python/dl_on_flink_pytorch/pytorch_context.py
dl-on-flink-pytorch/src/test/resources/all_gather.py
dl-on-flink-pytorch/src/test/resources/inference.py
dl-on-flink-pytorch/src/test/resources/with_input.py
dl-on-flink-pytorch/src/test/resources/with_input_iter.py

Rename PytorchContext to PyTorchContext
Rename PytorchContext to PyTorchContext

Rename PytorchContext to PyTorchContext

---

.github/workflows/prepare-release.yaml

Fix prepare release workflow
Fix prepare release workflow

Fix prepare release workflow

---

dl-on-flink-tensorflow-2.x/python/setup.py
dl-on-flink-tensorflow/python/setup.py

Specify protobuf version for dl-on-flink-tensorflow wheel build
Specify protobuf version for dl-on-flink-tensorflow wheel build

Specify protobuf version for dl-on-flink-tensorflow wheel build

---

examples/pytorch-on-flink/linear/flink_train.py
examples/tensorflow-on-flink/linear/flink_train.py

Correcting the input_type of the examples.
Correcting the input_type of the examples.

Fix examples

---

dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/node/runner/CommonMLRunner.java
dl-on-flink-framework/src/main/java/org/flinkextended/flink/ml/cluster/rpc/NodeServer.java
dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/NodeOperator.java
dl-on-flink-operator/src/main/java/org/flinkextended/flink/ml/operator/ops/inputformat/AbstractNodeInputFormat.java

NodeServer is interrupted periodically if it is not terminated on time
NodeServer is interrupted periodically if it is not terminated on time

NodeServer is interrupted periodically if it is not terminated on time

---

dl-on-flink-tensorflow-2.x/python/setup.py
dl-on-flink-tensorflow/python/setup.py

Specify grpcio version upper bound
Specify grpcio version upper bound

Specify grpcio version upper bound

---

doc/quick-start/quick_start_pytorch.md

Fix typo in quick_start_pytorch.md
Fix typo in quick_start_pytorch.md

Fix typo in quick_start_pytorch.md

---

dl-on-flink-dist/pom.xml
dl-on-flink-examples/dl-on-flink-examples-pytorch/pom.xml
dl-on-flink-examples/dl-on-flink-examples-tensorflow-2.x/pom.xml
dl-on-flink-examples/dl-on-flink-examples-tensorflow/pom.xml
dl-on-flink-examples/pom.xml
dl-on-flink-framework/pom.xml
dl-on-flink-framework/python/dl_on_flink_framework/version.py
dl-on-flink-framework/src/test/java/org/flinkextended/flink/ml/util/SysUtilTest.java
dl-on-flink-lib/pom.xml
dl-on-flink-operator/pom.xml
dl-on-flink-pytorch/pom.xml
dl-on-flink-pytorch/python/dl_on_flink_pytorch/version.py
dl-on-flink-tensorflow-2.x/pom.xml
dl-on-flink-tensorflow-2.x/python/dl_on_flink_tensorflow/version.py
dl-on-flink-tensorflow-common/pom.xml
dl-on-flink-tensorflow/pom.xml
dl-on-flink-tensorflow/python/dl_on_flink_tensorflow/version.py
doc/quick-start/quick_start_pytorch.md
doc/quick-start/quick_start_pytorch_estimator.md
doc/quick-start/quick_start_tensorflow_1.15.md
doc/quick-start/quick_start_tensorflow_2.4.md
doc/quick-start/quick_start_tensorflow_estimator_1.15.md
doc/quick-start/quick_start_tensorflow_estimator_2.4.md
pom.xml

Bump version to 0.6.0-SNAPSHOT
Bump version to 0.6.0-SNAPSHOT

Bump version to 0.6.0-SNAPSHOT
